version: "3.0"
services:
  backend:
   build: .
   container_name: backend-flask
   ports:
     - 5000:5000
  
  frontend:
    image: nginx:alpine
    container_name: frontend-flask
    ports:
      - 8080:8080
    volumes:
      - ./nginx.config:/usr/share/nginx/html:ro
    depends_on:
      - backend

  


